/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 girl_speedsculpt.glb 
Author: mrrobot (https://sketchfab.com/mrrobot)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/girl-speedsculpt-9c97d319c4754b1ba0465ccd9dcc1b77
Title: Girl speedsculpt
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Girl(props) {
  const { nodes, materials } = useGLTF('/models/girl_speedsculpt.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.019, 0, 0.568]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.113}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Merged_Extract6_material0_0.geometry} material={materials.material0} />
          <mesh geometry={nodes.Merged_Extract6_material0_0_1.geometry} material={materials.material0} />
          <mesh geometry={nodes.Merged_Extract6_material0_0_2.geometry} material={materials.material0} />
          <mesh geometry={nodes.Merged_Extract6_material0_0_3.geometry} material={materials.material0} />
          <mesh geometry={nodes.Merged_Extract6_material0_0_4.geometry} material={materials.material0} />
          <mesh geometry={nodes.Merged_Extract6_material0_0_5.geometry} material={materials.material0} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/girl_speedsculpt.glb')
